// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Server struct {
	ID   string  `json:"id"`
	Name *string `json:"name"`
}

type SignPayload struct {
	User  *User   `json:"user"`
	Token *string `json:"token"`
	Error *string `json:"error"`
}

type SigninInput struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

type SignupInput struct {
	Email                string `json:"email"`
	Mobile               string `json:"mobile"`
	Password             string `json:"password"`
	PasswordConfirmation string `json:"passwordConfirmation"`
}

type User struct {
	Email   string    `json:"email"`
	Servers []*Server `json:"servers"`
}
